[package]
name = "vimiwm"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.9", features = ["deprecated", "derive", "unicode"] }
smithay = { git = "https://github.com/Smithay/smithay.git", version = "0.3.0", branch = "master" }
